export default {
  portfolioOf: "Glauco Pater's Photography",
  home: 'Home',
  author: 'Glauco Pater',
  galleries: 'Galleries',
  publishedAt: 'Published',
  details: 'Details',
  back: 'Back',
  open: 'Open',
  prev: 'Prev',
  next: 'Next',
  browse: 'Portfolio of Glauco Pater',
  explore: 'Portfolio of Glauco Pater',
  empty: '',
  rights: '© All rights reserved',
};
