export default {
  portfolioOf: 'Glimpse',
  home: 'Home',
  author: 'Glauco Pater',
  contact: 'glauco(dot)pater(at)@gmail.com',
  galleries: 'Galleries',
  publishedAt: 'Published',
  details: 'Details',
  back: 'Back',
  open: 'Open',
  prev: 'Prev',
  next: 'Next',
  explore: 'Portfolio of Glauco Pater',
  empty: '',
  rights: '© All rights reserved',
  backTo: 'Back to:',
  disclaimer: 'Legal disclaimer',
  loading: 'Loading ...',
};
